---
title: "Final Project Data 211"
author: "Charles Sandahl"
date: "2025-04-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(tidyverse)
library(knitr)
```

# Data
```{r}
bikeData = read.csv("C:/Users/sanda/R/METRO DATA 211 SPRING 2025/final_project/bike_trips.csv")
```


$\mu$ is the average time it takes to commute to work on my bike

$H_0$: $\mu_1$ = $\mu_2$ = $\mu_3$

$H_a$: $\mu_i \ne \mu_j$ 

# AVNOVA test
```{r}
anova = aov(time ~path, data = bikeData)
summary(anova)
```

$p-value = 0.316$ which is greater than $\alpha=0.05$. We fail to reject the $H_0$. So, at $5\%$ significance level, we do not have enough evidence to conclude that the average commute time is significantly different between the three routes.

# Graph
```{r}
means = bikeData %>%
  group_by(path) %>% 
  summarise(mean_time = mean(time, na.rm = TRUE))

ggplot(data = bikeData, aes(x = path, y = time)) +
  geom_point(size = 2) +
  geom_point(data = means, aes(y = mean_time),
             colour = "red", size = 5) +
  labs(title = "Commute Times by Route",
       x = "Route", y = "Time (seconds)")
```

